version: '3.9'

services:
  db:
    image: postgis/postgis:15-3.4-alpine
    container_name: easybody-db
    environment:
      POSTGRES_DB: ${DB_NAME:-easybody_db}
      POSTGRES_USER: ${DB_USERNAME:-easybody_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-easybody_password_2024}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/initdb:/docker-entrypoint-initdb.d:ro
    networks:
      - easybody-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres} -d ${DB_NAME:-easybody}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: easybody-backend
    container_name: easybody-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-local}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-easybody_db}
      DB_USERNAME: ${DB_USERNAME:-easybody_user}
      DB_PASSWORD: ${DB_PASSWORD:-easybody_password_2024}
    ports:
      - "${APP_PORT:-8080}:8080"
    networks:
      - easybody-net
    restart: unless-stopped

volumes:
  db-data:

networks:
  easybody-net:
