services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: easybody-backend
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: easybody
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - backend

  db:
    image: postgis/postgis:15-3.4-alpine
    environment:
      POSTGRES_DB: easybody
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
