# Fly.io deployment configuration
# https://fly.io/docs/reference/configuration/

app = "easybody-api"
primary_region = "sin" # Singapore

[build]
  dockerfile = "Dockerfile"

[env]
  SPRING_PROFILES_ACTIVE = "aws"
  AWS_ENABLED = "false"
  SHOW_SQL = "false"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "30s"
    interval = "15s"
    method = "GET"
    timeout = "5s"
    path = "/actuator/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

# PostgreSQL Database
# Run: fly postgres create --name easybody-db --region sin
# Then: fly postgres attach easybody-db
