# Render.com deployment configuration
# https://render.com/docs/yaml-spec

services:
  # Spring Boot API Service
  - type: web
    name: easybody-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: singapore
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: aws
      - key: DB_HOST
        fromDatabase:
          name: easybody-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: easybody-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: easybody-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: easybody-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: easybody-db
          property: password
      - key: CORS_ALLOWED_ORIGINS
        value: https://aws-ws-fe.vercel.app,http://localhost:3000
      - key: AWS_ENABLED
        value: false
      - key: SHOW_SQL
        value: false

databases:
  # PostgreSQL Database with PostGIS
  - name: easybody-db
    databaseName: easybody
    user: postgres
    plan: free
    region: singapore
    postgresMajorVersion: 15
    # Note: Free tier expires after 90 days
    # After that, upgrade to paid plan ($7/month) or migrate to external DB
