spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://db:5432/easybody
    username: easybody
    password: easybody
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true

sql:
  init:
    mode: never
