spring:
  config:
    activate:
      on-profile: staging
  main:
    lazy-initialization: true
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}?sslmode=require}
    username: ${JDBC_DATABASE_USERNAME:${DB_USERNAME}}
    password: ${JDBC_DATABASE_PASSWORD:${DB_PASSWORD}}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 8
      initialization-fail-timeout: 60000
  jpa:
    show-sql: false
  flyway:
    baseline-on-migrate: true

sql:
  init:
    mode: never
