server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

spring:
  application:
    name: easybody
  profiles:
    default: local
  main:
    lazy-initialization: true
  datasource:
    hikari:
      initialization-fail-timeout: 60000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: true

aws:
  enabled: ${AWS_ENABLED:false}
  region: ${AWS_REGION:us-east-1}
  cognito:
    user-pool-id: ${COGNITO_USER_POOL_ID:}
    client-id: ${COGNITO_CLIENT_ID:}
    jwks-url: ${COGNITO_JWKS_URL:}
  s3:
    bucket-name: ${S3_BUCKET_NAME:easybody-media}
    presigned-url-expiration: ${S3_PRESIGNED_TTL:3600}
  sqs:
    image-moderation-queue: ${SQS_IMAGE_QUEUE_URL:}
  cloudwatch:
    namespace: EasyBody

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:3001,https://aws-ws-fe.vercel.app}

app:
  search:
    default-radius-km: 10
    max-radius-km: 100
  moderation:
    auto-reject-threshold: 0.8
    manual-review-threshold: 0.5
  pagination:
    default-page-size: 20
    max-page-size: 100

logging:
  level:
    root: INFO
    com.easybody: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot.actuate: DEBUG
    org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext: INFO
    org.hibernate.SQL: ${SQL_LOG_LEVEL:INFO}
