spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:easybody}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration,classpath:db/seed

sql:
  init:
    mode: never

app:
  auth:
    basic:
      enabled: true
      username: ${LOCAL_BASIC_AUTH_USERNAME:local-admin}
      password: ${LOCAL_BASIC_AUTH_PASSWORD:local-password}
      role: ${LOCAL_BASIC_AUTH_ROLE:ADMIN}
